name: 项目重命名

on:
  workflow_dispatch:
    inputs:
      new_name:
        description: '请输入新名称（默认使用仓库名）'
        required: false
        type: string

      old_name:
        description: '请输入原名称（默认使用仓库名）'
        required: true
        type: string
        default: stm32f103_template
        
jobs:
  modify-files:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      OLD: ${{ inputs.old_name || github.event.repository.name }}
      NEW: ${{ inputs.new_name || github.event.repository.name }}
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Rename
        run: |
          sed -i "s|$OLD|$NEW|g" Makefile
          sed -i "s|$OLD|$NEW|g" "$OLD.ioc"
          mv "$OLD.ioc" "$NEW.ioc"

      - name: Commit and push changes
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          if [[ -n $(git status --porcelain) ]]; then
            git commit -m "重命名 $OLD 为 $NEW"
            git push
          else
            echo "没有需要提交的修改"
          fi